import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'path';
import fs from 'fs';

// Load HTTPS certs if available (generated by mkcert)
function loadCerts() {
  const certDir = path.resolve(__dirname, '.certs');

  try {
    const files = fs.readdirSync(certDir);
    const certFile = files.find(f => f.endsWith('.pem') && !f.includes('-key'));
    const keyFile = files.find(f => f.endsWith('-key.pem'));
    if (certFile && keyFile) {
      return {
        cert: fs.readFileSync(path.join(certDir, certFile)),
        key: fs.readFileSync(path.join(certDir, keyFile)),
      };
    }
  } catch {
    // No certs directory — fall back to HTTP
  }
  return undefined;
}

const https = loadCerts();

export default defineConfig({
  base: process.env.GITHUB_ACTIONS ? '/SpineApp/' : '/',
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  plugins: [
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectRegister: false,
      manifest: false,
      devOptions: {
        enabled: true,
        type: 'module',
      },
      injectManifest: {
        globPatterns: [
          '**/*.{js,css,html,png,mp3,json}',
        ],
      },
    }),
  ],
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          chart: ['chart.js', 'chartjs-adapter-date-fns', 'date-fns'],
        },
      },
    },
  },
  server: {
    host: true,
    https: https,
  },
  preview: {
    host: true,
    port: 4173,
    https: https,
  },
});
